"""Render one persisted analysis to an audit-grade markdown report.

Pure function of the report row (no I/O): the service layer owns writing the file.
The appendix lists every tool call with its arguments and result — the artifact an
external audit firm reviews (PRD-B §4). Markdown is the canonical format; PDF export
is a documented follow-up (``pandoc {id}.md -o {id}.pdf`` works on the output as-is).
"""

from __future__ import annotations

import json

from .models import AnalysisReportRow


def _fence(content: str, lang: str = "json") -> str:
    return f"```{lang}\n{content}\n```"


def render_markdown(row: AnalysisReportRow) -> str:
    """Render the full audit report for ``row`` as markdown."""
    trace = json.loads(row.trace_json)
    citations = json.loads(row.citations_json)
    session_notes = json.loads(getattr(row, "session_notes_json", None) or "[]")

    lines = [
        f"# AML Analysis Report `{row.id}`",
        "",
        f"- **Account:** `{row.account_id}`" + (f" (bank `{row.bank}`)" if row.bank else ""),
        f"- **Pipeline:** {row.pipeline}",
        f"- **Model:** {row.model or 'n/a'} ({row.model_digest or 'digest n/a'})",
        f"- **Created:** {row.created_at}",
        f"- **Started / finished:** {row.started_at or 'n/a'} / {row.finished_at or 'n/a'}"
        + (f" ({row.wall_clock_s:.1f}s)" if row.wall_clock_s is not None else ""),
        "",
        "## Decision",
        "",
        f"**{row.decision.upper()}**",
        "",
        "## Rationale",
        "",
        row.rationale or "_(none recorded)_",
        "",
        "## Rule citations",
        "",
    ]
    if citations:
        lines.extend(f"- {c}" for c in citations)
    else:
        lines.append("_(no rulebook/corpus citations recorded)_")

    lines += [
        "",
        "---",
        "",
        "## Appendix — session context provided to the agent",
        "",
    ]
    if session_notes:
        lines.append(
            f"{len(session_notes)} prior-analysis summar"
            f"{'y' if len(session_notes) == 1 else 'ies'} from the API session were "
            "injected into the case input (the agent modules themselves are stateless):"
        )
        lines.append("")
        lines.extend(f"- {note}" for note in session_notes)
    else:
        lines.append("_(none — this analysis ran without prior session context)_")

    lines += [
        "",
        "## Appendix — full tool-call trace",
        "",
        f"{len(trace)} tool call(s), in execution order. Row ids in results reference "
        "rows in the tabular store (`tabular_data_db.sqlite`).",
        "",
    ]
    for i, call in enumerate(trace, start=1):
        name = call.get("name", "unknown_tool")
        lines.append(f"### {i}. `{name}`")
        lines.append("")
        lines.append("**Arguments**")
        lines.append(_fence(json.dumps(call.get("args", {}), indent=2, ensure_ascii=False, default=str)))
        lines.append("")
        lines.append("**Result**")
        result = call.get("result", "")
        if isinstance(result, (dict, list)):
            lines.append(_fence(json.dumps(result, indent=2, ensure_ascii=False, default=str)))
        else:
            lines.append(_fence(str(result), lang="text"))
        lines.append("")

    lines += [
        "---",
        "",
        "_Generated by the AML compliance platform. Configuration default pipeline is "
        "selected by pre-registered evaluation (see dissertation §Results)._",
        "",
    ]
    return "\n".join(lines)
